//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeF.Redis.Page {
    
    
    public partial class ReportList {
        
        /// <summary>
        /// AnalyzeReportList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CafeF.Redis.Page.UserControl.Report.AnalyzeReportList AnalyzeReportList1;
        
        /// <summary>
        /// ucSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CafeF.Redis.Page.UserControl.StockView.Search ucSearch;
        
        /// <summary>
        /// LatestEvents1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CafeF.Redis.Page.UserControl.LichSuKien.LatestEvents LatestEvents1;
    }
}
