var strPE="";var strPEPaging="";var pagingPE=document.getElementById("pagingPE");var divData1EPS=document.getElementById("divData1EPS");var divData2EPS=document.getElementById("divData2EPS");var tab1EPS=document.getElementById("lstab1EPS");var tab2EPS=document.getElementById("lstab2EPS");divData2EPS.style.display="none";document.getElementById('txtIdxSameEPS').value=1;document.getElementById('txtIdxSamePE').value=1;function changeTabEPS(index)
{divData1EPS.style.display="none";divData2EPS.style.display="none";tab1EPS.style.color="";tab2EPS.style.color="";switch(index)
{case 1:divData1EPS.style.display="";tab1EPS.style.color="#cc0000";LoadSamePE(symbol,1,10);break;case 2:divData2EPS.style.display="";tab2EPS.style.color="#cc0000";if(strPEPaging=="")
LoadPaging(sym);else
pagingPE.innerHTML=strPEPaging;break;default:break;}}
changeTabEPS(1);function LoadSameEPS(symbol,index,size)
{document.getElementById("pagingnoteeps").innerHTML="Trang "+index+"/"+TotalPage+"(Tổng số "+TotalItem+" công ty)";$.ajax({type:"GET",url:"/Ajax/CungNganh/SameEPS.aspx",data:"symbol="+_symbol+"&PageIndex="+index+"&PageSize="+size,success:function(msg){document.getElementById("divData1EPSInner").innerHTML=msg;}});}
var symbol='<%= Symbol %>';function ViewPageNextPreviousEPS(index)
{var txtIdxSameEPS=document.getElementById('txtIdxSameEPS');var currSameEPSIdx=parseInt(txtIdxSameEPS.value)+parseInt(index);if(currSameEPSIdx<1)return;var iTotalPageSameEPS=TotalPage;if(currSameEPSIdx>iTotalPageSameEPS)return;var preIndex=txtIdxSameEPS.value;var preObject=document.getElementById("aSameEPS"+preIndex);var currObject=document.getElementById("aSameEPS"+currSameEPSIdx);preObject.className="";currObject.className="current";txtIdxSameEPS.value=currSameEPSIdx;LoadSameEPS(symbol,currSameEPSIdx,10);}
function ViewPageSameEPSByIndex(index){var txtIdxSameEPS=document.getElementById('txtIdxSameEPS');var preIndex=txtIdxSameEPS.value;var preObject=document.getElementById("aSameEPS"+preIndex);var currObject=document.getElementById("aSameEPS"+index);preObject.className="";currObject.className="current";txtIdxSameEPS.value=index;LoadSameEPS(symbol,index,10);}
function LoadSamePE(symbol,index,size)
{$.ajax({type:"GET",url:"/Ajax/CungNganh/SamePE.aspx",data:"symbol="+_symbol+"&PageIndex="+index+"&PageSize="+size,success:function(msg){document.getElementById("divData2EPSInner").innerHTML=msg;}});}
function LoadPaging(symbol)
{$.ajax({type:"GET",url:"/Ajax/CungNganh/GenPagingSamePE.aspx",data:"symbol="+_symbol,success:function(msg){document.getElementById("pagingPE").innerHTML=msg;}});}
function ViewPageNextPreviousPE(index)
{var txtIdxSamePE=document.getElementById('txtIdxSamePE');var currSamePEIdx=parseInt(txtIdxSamePE.value)+parseInt(index);if(currSamePEIdx<1)return;var iTotalPageSamePE=document.getElementById('txtTotalPagePE').value;if(currSamePEIdx>iTotalPageSamePE)return;var preIndex=txtIdxSamePE.value;var preObject=document.getElementById("aSamePE"+preIndex);var currObject=document.getElementById("aSamePE"+currSamePEIdx);preObject.className="";currObject.className="current";txtIdxSamePE.value=currSamePEIdx;LoadSamePE(symbol,currSamePEIdx,10);document.getElementById('pagingnoteepspe').innerHTML="Trang "+index+"/"+document.getElementById('txtTotalPagePE').value+"(Tổng số "+document.getElementById('txtTotalItemPE').value+" công ty)";}
function ViewPageSamePEByIndex(index){var txtIdxSamePE=document.getElementById('txtIdxSamePE');var preIndex=txtIdxSamePE.value;var preObject=document.getElementById("aSamePE"+preIndex);var currObject=document.getElementById("aSamePE"+index);preObject.className="";currObject.className="current";txtIdxSamePE.value=index;LoadSamePE(symbol,index,10);document.getElementById('pagingnoteepspe').innerHTML="Trang "+index+"/"+document.getElementById('txtTotalPagePE').value+"(Tổng số "+document.getElementById('txtTotalItemPE').value+" công ty)";}